FROM php:8.5-cli-alpine
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions @composer
RUN install-php-extensions ast ctype filter mbstring pcntl pcov
RUN apk add --no-cache gnupg
ENV COMPOSER_ROOT_VERSION=1.0.0
WORKDIR /app
COPY --parents configs src tests vendor composer.json composer.lock ./
